/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
    checkstyle
    jacoco
}
val javaVersion = versionCatalogs.find("libs").get().findVersion("java").get().toString()

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.14.0")
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("6.0.1")
        }
    }
}
// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

checkstyle {
    toolVersion = versionCatalogs.find("libs").get().findVersion("checkstyle").get().toString()
    configProperties =
        mapOf(
            "cache.file" to
                    file("$rootDir/config/checkstyle/checkstyle_cache").absolutePath,
            "jdk.version" to javaVersion
        )
}

jacoco {
    toolVersion = versionCatalogs.find("libs").get().findVersion("jacoco").get().toString()
}

tasks.withType(Checkstyle::class.java) {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

tasks.test {
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    reports {
        xml.required = false
        csv.required = false
    }
}
